---
name: Graphics-DZI
version: 0.05
author:
  - 'Robert Barta <drrho@cpan.org>'
abstract: DeepZoom Image Pyramid Generation
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Basename: ''
  File::Path: ''
  File::Slurp: ''
  Getopt::Long: ''
  Image::Magick: ''
  List::MoreUtils: ''
  Log::Log4perl: ''
  Moose: ''
  Pod::Usage: ''
  Test::Exception: ''
  Test::More: ''
  Test::Pod::Coverage: ''
configure_requires:
  Module::Build: 0.340201
provides:
  Graphics::DZI:
    file: lib/Graphics/DZI.pm
    version: 0.05
  Graphics::DZI::A4:
    file: lib/Graphics/DZI/A4.pm
    version: 0.02
  Graphics::DZI::Document:
    file: lib/Graphics/DZI/Document.pm
    version: 0.01
  Graphics::DZI::Files:
    file: lib/Graphics/DZI/Files.pm
    version: 0.02
  Graphics::DZI::Overlay:
    file: lib/Graphics/DZI/Overlay.pm
    version: 0.01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
